# Generated by Django 5.2 on 2025-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery option...', max_length=100, unique=True)),
                ('estimated_delivery_time', models.CharField(blank=True, help_text='Estimated delivery timeframe...', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this delivery option currently available...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
                'ordering': ['name'],
            },
        ),
    ]
