# Generated by Django 5.2 on 2025-04-07 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='base_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base delivery charge for this option (PKR). Set to 0.00 for free delivery.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, help_text="Estimated delivery timeframe (e.g., '24-48 hours', 'Same Day'). Can be updated in Admin.", max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this delivery option currently available for selection/use?'),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='name',
            field=models.CharField(help_text='Name of the delivery option (e.g., TCS, Leopards Courier, Local Rider, Urgent Delivery).', max_length=100, unique=True),
        ),
    ]
