# Generated by Django 5.2 on 2025-04-07 19:25

import shipping_delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_delivery', '0002_deliveryoption_base_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the logo for this delivery service (optional).', null=True, upload_to=shipping_delivery.models.delivery_option_logo_path),
        ),
    ]
