# Generated by Django 5.2 on 2025-04-06 22:24

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_requires_prescription',
            field=models.BooleanField(default=False, editable=False, help_text='Indicates if any item in the order requires a prescription.'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.FileField(blank=True, help_text='Upload prescription file if required (PDF, JPG, PNG).', null=True, upload_to=orders.models.prescription_upload_path),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('NA', 'Not Required'), ('PENDING_UPLOAD', 'Pending Upload'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='NA', help_text='Verification status of the uploaded prescription.', max_length=25),
        ),
    ]
