# Generated by Django 5.2 on 2025-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_requires_prescription_order_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_otp_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the order confirmation OTP has been successfully verified.'),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Generated OTP code for order confirmation.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, help_text='Time when the OTP code expires.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_OTP', 'Awaiting OTP Verification'), ('AWAITING_RX', 'Awaiting Prescription'), ('PROCESSING', 'Processing'), ('SOURCING', 'Sourcing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
