# Generated by Django 5.2 on 2025-04-07 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_number_alter_order_created_at'),
        ('shipping_delivery', '0003_deliveryoption_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_service',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery charge applied at the time of order creation.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping_delivery.deliveryoption', verbose_name='Assigned Delivery Option'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of items before delivery charge.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, help_text='Total amount including items and delivery charge.', max_digits=12),
        ),
    ]
