# Generated by Django 5.2 on 2025-04-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Auto-generated if left blank.', max_length=255, unique=True)),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('composition', models.TextField(blank=True, help_text='Ingredients or chemical composition.')),
                ('usage_instructions', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum Retail Price', max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price at which the product was procured.', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price at which the product is sold.', max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, help_text='Is the product available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name', 'sku'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['brand'], name='products_pr_brand_i_dc6890_idx'), models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx')],
            },
        ),
    ]
