# Generated by Django 6.0 on 2026-01-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_brand_i_dc6890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_avai_c23034_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Uses and benefits of the medicine.'),
        ),
        migrations.AddField(
            model_name='product',
            name='fact_box_action_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fact_box_chemical_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fact_box_habit_forming',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fact_box_therapeutic_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Mechanism of action.'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='Dosage instructions (How to take it).'),
        ),
        migrations.AddField(
            model_name='product',
            name='quick_tips',
            field=models.TextField(blank=True, help_text='Expert advice and tips for the patient.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_alcohol',
            field=models.TextField(blank=True, default='Consult your doctor before consuming alcohol.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_breastfeeding',
            field=models.TextField(blank=True, default='Consult your doctor before use during breastfeeding.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_driving',
            field=models.TextField(blank=True, default='Do not drive if you feel dizzy or sleepy.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_kidney',
            field=models.TextField(blank=True, default='Caution is advised in patients with kidney disease.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_liver',
            field=models.TextField(blank=True, default='Caution is advised in patients with liver disease.'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_pregnancy',
            field=models.TextField(blank=True, default='Consult your doctor before use during pregnancy.'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Common and serious side effects.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Salt Composition (e.g. Cefpodoxime Proxetil (200mg))'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='General introduction or overview.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier.', max_length=255, unique=True),
        ),
    ]
