# Generated by Django 6.0 on 2026-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_categor_9edb3d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.TextField(blank=True, help_text='Dosage info by age and weight.'),
        ),
        migrations.AddField(
            model_name='product',
            name='interactions',
            field=models.TextField(blank=True, help_text='Drug-drug and drug-food interactions.'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='missed_dose',
            field=models.TextField(blank=True, help_text='What to do if a dose is missed.'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, help_text='How to store the medicine.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='1mg-style Introduction'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_it_works',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_alcohol',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_breastfeeding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_driving',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_kidney',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_liver',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_pregnancy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
