# Generated by Django 6.0 on 2026-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_products_pr_sku_ca0cdc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Uses and clinical benefits.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Salt Composition (e.g. Cefpodoxime Proxetil (200mg))'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='General patient-friendly introduction.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.TextField(blank=True, help_text='Dosage guidelines by age and weight.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Mechanism of action.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='General instructions on consumption.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Search engine description (max 155 chars).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO keywords separated by commas.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Search engine title (max 60 chars).', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='missed_dose',
            field=models.TextField(blank=True, help_text='Instructions for a forgotten dose.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Comprehensive list of common and rare side effects.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique Stock Keeping Unit', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, help_text='Storage temperature and environment advice.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
    ]
